import type { Locale } from "./site";

export const privacyContent = {
  ko: {
    title: "개인정보처리방침",
    description: "WOORI.TODAY 전체 웹 서비스의 개인정보 처리와 쿠키, 분석 및 광고 관련 안내입니다.",
    intro: "WOORI.TODAY는 이용자의 개인정보를 소중히 여기며, 서비스 제공에 필요한 범위에서 정보를 신중하게 처리합니다. 이 방침은 WOORI.TODAY Portal, Calculator, Tools 및 MoneyBook의 공개 웹 서비스 영역에 적용됩니다. MoneyBook 계정 및 가계부 기능에는 별도 안내도 적용될 수 있습니다.",
    updated: "최종 수정일: 2026년 10월 9일",
    sections: [
      { title: "1. 자동으로 수집될 수 있는 정보", body: "웹사이트를 이용할 때 접속 일시, 방문한 페이지, 브라우저·운영체제·기기 정보, IP 주소 또는 이를 바탕으로 한 대략적인 지역, 쿠키와 유사 기술의 식별 정보, 서비스 이용 기록이 자동으로 처리될 수 있습니다. 정보는 서비스 운영, 보안, 이용 현황 파악 및 개선을 위해 필요한 범위에서 다뤄집니다. 이용자가 입력하지 않은 개인정보를 당사가 직접 수집한다고 의미하지는 않습니다." },
      { title: "2. Google Analytics 4", body: "방문자 수, 페이지 조회, 유입 경로와 서비스 이용 패턴을 파악하고 서비스를 개선하기 위해 Google Analytics 4를 사용합니다. Google Analytics는 쿠키 또는 유사 기술을 이용해 이용 및 기기 관련 정보를 수집·측정할 수 있습니다. 수집·처리 방식은 Google의 설정과 정책 및 이용자의 동의 선택에 따라 달라질 수 있습니다." },
      { title: "3. Google AdSense 및 광고", body: "서비스 운영을 위해 Google AdSense를 통한 광고를 제공할 수 있습니다. 광고 제공 과정에서 Google 또는 광고 파트너가 쿠키, 광고 식별자, 브라우저·기기 정보, 광고 노출 및 상호작용 정보를 처리할 수 있습니다. 개인 맞춤 광고 여부와 데이터 사용은 지역, 설정 및 이용자의 선택에 따라 달라질 수 있습니다." },
      { title: "4. 쿠키, 동의 관리 및 Consent Mode", body: "분석과 광고 목적을 위해 쿠키 또는 유사 기술이 사용될 수 있습니다. 유럽 경제 지역(EEA), 영국, 스위스 등 관련 지역의 이용자에게 적용되는 설정에 따라 동의 메시지가 표시될 수 있습니다. Google의 Consent Management Platform(CMP)이 활성화된 경우 동의·거부 또는 세부 옵션을 선택하거나 변경할 수 있습니다. Consent Mode가 설정된 경우 선택 내용은 Google 태그에 전달되어 관련 측정·광고 기능에 반영될 수 있습니다. 브라우저 설정에서도 쿠키를 차단하거나 삭제할 수 있으며, 이 경우 일부 기능이 달라질 수 있습니다." },
      { title: "5. 제3자 서비스", body: "Google Analytics와 Google AdSense 등 외부 서비스는 각자의 개인정보처리방침과 설정에 따라 정보를 처리할 수 있습니다. 외부 서비스의 데이터 처리와 이용자 선택에 관한 자세한 내용은 해당 제공자의 안내를 확인해 주세요." },
      { title: "6. MoneyBook 계정 및 가계부 정보", body: "MoneyBook은 회원가입·로그인과 가계부 기능을 제공하는 별도 서비스 영역입니다. 계정, 사용자가 입력한 가계부 데이터 및 해당 기능의 구체적인 처리 방식은 MoneyBook 전용 개인정보처리방침도 함께 확인해 주세요." },
      { title: "7. 보관 및 삭제", body: "정보는 이용 목적을 달성하거나 관련 법령 및 서비스 운영상 필요한 범위에서 보관될 수 있습니다. 이용자가 직접 제공한 정보의 삭제를 원하면 사이트의 공식 문의 채널을 통해 요청할 수 있습니다. Google 등 외부 서비스가 처리하는 정보의 보관·삭제는 해당 서비스의 정책과 도구가 적용될 수 있습니다." },
      { title: "8. 이용자의 선택", body: "브라우저 설정을 통해 쿠키를 제한하거나 삭제할 수 있습니다. Google 계정의 광고 개인화 설정을 변경할 수 있으며, 동의 메시지가 제공되는 경우 동의 상태나 선택 항목을 변경할 수 있습니다. 브라우저에서 쿠키를 차단하면 일부 서비스 기능이나 환경설정이 제대로 작동하지 않을 수 있습니다." },
      { title: "9. 문의", body: "개인정보 관련 문의, 정보 삭제 요청 또는 이 방침에 대한 의견은 사이트의 공식 문의 채널을 통해 접수할 수 있습니다." },
      { title: "10. 방침의 변경 및 시행", body: "서비스 또는 관련 기준의 변경에 따라 이 방침을 업데이트할 수 있습니다. 변경 내용은 이 페이지에 게시하며, 이 방침은 2026년 10월 9일부터 적용됩니다." },
    ],
    googleLabel: "Google 개인정보처리방침",
    moneyLabel: "MoneyBook 개인정보처리방침",
  },
  en: {
    title: "Privacy Policy",
    description: "How WOORI.TODAY web services handle information, cookies, analytics, and advertising.",
    intro: "WOORI.TODAY takes privacy seriously and handles information thoughtfully, within the scope needed to provide its services. This policy covers the WOORI.TODAY Portal, Calculator, Tools, and the public web areas of MoneyBook. Separate notices may also apply to MoneyBook accounts and bookkeeping features.",
    updated: "Last updated: October 9, 2026",
    sections: [
      { title: "1. Information that may be collected automatically", body: "When you use our websites, information may be processed automatically, such as the time of access, pages visited, browser, operating system and device details, IP address or an approximate location derived from it, identifiers from cookies or similar technologies, and service usage records. This information is handled as needed to operate and secure the services, understand usage, and make improvements. This does not mean that we directly collect personal details that you have not entered." },
      { title: "2. Google Analytics 4", body: "We use Google Analytics 4 to understand visitor numbers, page views, referral sources, and patterns of service use, and to improve our services. Google Analytics may use cookies or similar technologies to collect and measure usage and device-related information. How information is collected and processed may depend on Google's settings and policies and your consent choices." },
      { title: "3. Google AdSense and advertising", body: "We may provide advertising through Google AdSense to support our services. In this process, Google or advertising partners may process cookies, advertising identifiers, browser or device details, and information about ad impressions and interactions. Whether ads are personalized and how data is used may vary by location, settings, and your choices." },
      { title: "4. Cookies, consent controls, and Consent Mode", body: "Cookies or similar technologies may be used for analytics and advertising. Depending on the configuration applicable to users in the European Economic Area (EEA), the United Kingdom, Switzerland, and other relevant regions, a consent message may be shown. If Google's Consent Management Platform (CMP) is enabled, you may be able to consent, decline, or manage options. If Consent Mode is configured, your choices may be communicated to Google tags and reflected in related measurement and advertising features. You can also block or delete cookies in your browser settings; some features may then work differently." },
      { title: "5. Third-party services", body: "External services, including Google Analytics and Google AdSense, may process information under their own privacy policies and settings. Please review the provider's information for details about its data practices and available controls." },
      { title: "6. MoneyBook accounts and bookkeeping data", body: "MoneyBook is a separate service area with registration, sign-in, and bookkeeping features. Please also consult the MoneyBook privacy policy for details about accounts, bookkeeping data you enter, and how those features handle information." },
      { title: "7. Retention and deletion", body: "Information may be kept for as long as needed for its purpose or as required for applicable legal or service needs. If you want information you provided directly to be deleted, you can make a request through the site's official contact channel. Retention and deletion of information handled by Google and other external services may be governed by their own policies and tools." },
      { title: "8. Your choices", body: "You can limit or delete cookies through your browser settings. You can change ad personalization settings in your Google Account, and, where a consent message is available, change your consent status or selected options. Blocking cookies in your browser may affect some service features or preferences." },
      { title: "9. Contact", body: "For privacy questions, requests to delete information, or comments about this policy, please use the site's official contact channel." },
      { title: "10. Changes and effective date", body: "We may update this policy as our services or applicable requirements change. Updates will be posted on this page. This policy is effective October 9, 2026." },
    ],
    googleLabel: "Google Privacy Policy",
    moneyLabel: "MoneyBook Privacy Policy",
  },
  ja: {
    title: "プライバシーポリシー",
    description: "WOORI.TODAYのウェブサービスにおける情報、Cookie、アクセス解析、広告の取り扱いについてご案内します。",
    intro: "WOORI.TODAYはプライバシーを大切にし、サービスの提供に必要な範囲で情報を慎重に取り扱います。本ポリシーはWOORI.TODAY Portal、Calculator、ToolsおよびMoneyBookの公開ウェブサービスに適用されます。MoneyBookのアカウントや家計簿機能には、別途の案内が適用される場合があります。",
    updated: "最終更新日：2026年10月9日",
    sections: [
      { title: "1. 自動的に取得されることのある情報", body: "ウェブサイトの利用時に、アクセス日時、閲覧ページ、ブラウザー・OS・端末に関する情報、IPアドレスまたはそこから推定されるおおよその地域、Cookieなどの技術による識別情報、サービスの利用記録が自動的に処理されることがあります。これらはサービスの運営や安全確保、利用状況の把握、改善に必要な範囲で取り扱います。利用者が入力していない個人情報を当社が直接取得するという意味ではありません。" },
      { title: "2. Google Analytics 4", body: "訪問者数、ページ閲覧数、流入元、サービスの利用傾向を把握し、サービスを改善するためにGoogle Analytics 4を利用しています。Google AnalyticsはCookieなどを使って、利用状況や端末に関する情報を収集・測定することがあります。収集・処理の方法は、Googleの設定やポリシー、利用者の同意内容によって異なる場合があります。" },
      { title: "3. Google AdSenseと広告", body: "サービスの運営を支えるため、Google AdSenseによる広告を掲載することがあります。広告の提供にあたり、Googleまたは広告パートナーがCookie、広告識別子、ブラウザー・端末情報、広告の表示や操作に関する情報を処理する場合があります。パーソナライズ広告の有無やデータの利用方法は、地域、設定、利用者の選択により異なります。" },
      { title: "4. Cookie、同意管理、Consent Mode", body: "アクセス解析や広告のためにCookieなどの技術を使用する場合があります。欧州経済領域（EEA）、英国、スイスなど、関連地域に適用される設定に応じて同意メッセージが表示されることがあります。GoogleのConsent Management Platform（CMP）が有効な場合、同意・拒否や詳細な設定を選択・変更できることがあります。Consent Modeが設定されている場合、選択内容がGoogleタグに伝達され、関連する測定・広告機能に反映されることがあります。ブラウザーの設定からCookieを制限・削除することもできますが、一部機能に影響する場合があります。" },
      { title: "5. 外部サービス", body: "Google AnalyticsやGoogle AdSenseなどの外部サービスは、それぞれのプライバシーポリシーや設定に基づいて情報を処理することがあります。データの取り扱いや利用者向けの設定については、各提供者の案内をご確認ください。" },
      { title: "6. MoneyBookのアカウントと家計簿データ", body: "MoneyBookは、会員登録・ログインおよび家計簿機能を備えた別サービス領域です。アカウント、利用者が入力した家計簿データ、各機能における情報の取り扱いについては、MoneyBook専用のプライバシーポリシーもあわせてご確認ください。" },
      { title: "7. 保管と削除", body: "情報は利用目的の達成に必要な期間、または適用法令やサービス運営上必要な範囲で保管されることがあります。利用者が直接提供した情報の削除を希望する場合は、サイトの公式お問い合わせ窓口からご依頼ください。Googleなど外部サービスが取り扱う情報の保管・削除には、各サービスのポリシーや機能が適用される場合があります。" },
      { title: "8. 利用者が選べること", body: "ブラウザーの設定からCookieを制限または削除できます。Googleアカウントで広告のパーソナライズ設定を変更でき、同意メッセージが表示される場合は同意状況や選択項目を変更できます。Cookieをブロックすると、一部の機能や設定が正しく動作しないことがあります。" },
      { title: "9. お問い合わせ", body: "プライバシーに関するご質問、情報の削除依頼、本ポリシーへのご意見は、サイトの公式お問い合わせ窓口からお寄せください。" },
      { title: "10. 改定と適用日", body: "サービスや関連する要件の変更に応じて、本ポリシーを更新することがあります。変更内容はこのページに掲載します。本ポリシーは2026年10月9日から適用されます。" },
    ],
    googleLabel: "Google プライバシーポリシー",
    moneyLabel: "MoneyBook プライバシーポリシー",
  },
  zh: {
    title: "隐私政策",
    description: "了解 WOORI.TODAY 各项网站服务如何处理信息、Cookie、访问分析和广告相关数据。",
    intro: "WOORI.TODAY 重视用户隐私，并在提供服务所需的范围内谨慎处理信息。本政策适用于 WOORI.TODAY Portal、Calculator、Tools 以及 MoneyBook 面向公众的网站服务。MoneyBook 的账户和记账功能也可能适用单独的说明。",
    updated: "最后更新：2026年10月9日",
    sections: [
      { title: "1. 可能自动收集的信息", body: "使用网站时，系统可能自动处理访问时间、浏览页面、浏览器/操作系统/设备信息、IP 地址或据此推测的大致地区、Cookie 等技术生成的标识信息以及服务使用记录。这些信息仅在运营和保障服务、了解使用情况及改进服务所需的范围内处理。这并不表示我们会直接收集用户未主动填写的个人资料。" },
      { title: "2. Google Analytics 4", body: "我们使用 Google Analytics 4 了解访客数量、页面浏览、访问来源和服务使用情况，以改进服务。Google Analytics 可能通过 Cookie 或类似技术收集并衡量使用情况及设备相关信息。具体收集和处理方式可能取决于 Google 的设置和政策，以及用户的同意选择。" },
      { title: "3. Google AdSense 与广告", body: "我们可能通过 Google AdSense 提供广告，以支持服务运营。在提供广告的过程中，Google 或广告合作伙伴可能处理 Cookie、广告标识符、浏览器或设备信息，以及广告展示和互动信息。是否展示个性化广告及数据使用方式可能因所在地区、设置和用户选择而异。" },
      { title: "4. Cookie、同意管理与 Consent Mode", body: "分析和广告可能使用 Cookie 或类似技术。根据适用于欧洲经济区（EEA）、英国、瑞士等相关地区用户的设置，网站可能显示同意提示。如果启用了 Google Consent Management Platform（CMP），用户可能可以同意、拒绝或管理具体选项。如果配置了 Consent Mode，用户的选择可能传递给 Google 标签，并用于相关测量和广告功能。用户也可以在浏览器设置中限制或删除 Cookie；这可能影响部分功能。" },
      { title: "5. 第三方服务", body: "Google Analytics、Google AdSense 等外部服务可能依据各自的隐私政策和设置处理信息。有关其数据处理方式及用户可用的控制选项，请参阅相应服务提供方的说明。" },
      { title: "6. MoneyBook 账户与记账数据", body: "MoneyBook 是提供注册、登录和记账功能的独立服务区域。有关账户、用户录入的记账数据及相关功能的信息处理方式，请同时参阅 MoneyBook 专用隐私政策。" },
      { title: "7. 保存与删除", body: "信息可能在实现使用目的所需的期限内，或依据适用法律及服务运营需要的范围内保存。如需删除用户直接提供的信息，可通过网站的官方联系渠道提出请求。Google 等外部服务处理的信息，其保存和删除可能适用相应服务自身的政策和工具。" },
      { title: "8. 用户的选择", body: "用户可以在浏览器设置中限制或删除 Cookie，也可以在 Google 账户中调整广告个性化设置。如果网站提供同意提示，用户可以更改同意状态或所选项目。屏蔽 Cookie 可能导致部分服务功能或偏好设置无法正常使用。" },
      { title: "9. 联系方式", body: "如有隐私相关问题、信息删除请求或对本政策的意见，请通过网站的官方联系渠道提交。" },
      { title: "10. 政策变更与生效日期", body: "我们可能根据服务或相关要求的变化更新本政策。更新内容将在本页面公布。本政策自2026年10月9日起生效。" },
    ],
    googleLabel: "Google 隐私权政策",
    moneyLabel: "MoneyBook 隐私政策",
  },
} satisfies Record<Locale, { title: string; description: string; intro: string; updated: string; sections: { title: string; body: string }[]; googleLabel: string; moneyLabel: string }>;
