export const origin = "https://www.woori.today";
export const locales = ["ko", "en", "ja", "zh"] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.some((locale) => locale === value);
export const localeNames: Record<Locale, string> = { ko: "한국어", en: "English", ja: "日本語", zh: "中文" };

export const messages = {
  ko: {
    title: "WOORI.TODAY | 가계부, 계산기, 온라인 도구",
    description: "공유 가계부, 금융·생활 계산기, 이미지·텍스트·개발 도구를 무료로 이용할 수 있는 생활 서비스 플랫폼.",
    home: "홈", money: "가계부", calculators: "계산기", tools: "도구",
    eyebrow: "매일 쓰는 생활 서비스를 한곳에서",
    headline: "일상에 필요한 서비스를 한곳에서",
    intro: "가계부부터 다양한 계산기와 온라인 도구까지, 일상에서 자주 필요한 기능을 간편하게 이용하세요.",
    start: "가계부 시작하기", seeCalculators: "계산기 보기", seeTools: "도구 보기",
    moneyTitle: "무료로 시작하는 공유 가계부",
    moneyDesc: "가족, 부부, 친구 또는 사용자를 추가해 하나의 가계부를 함께 관리하세요.",
    calcTitle: "필요한 계산을 빠르고 간편하게",
    calcDesc: "금융, 수학, 생활, 날짜 등 일상에서 필요한 다양한 계산기를 설치 없이 바로 사용할 수 있습니다.",
    toolsTitle: "설치 없이 바로 사용하는 온라인 도구",
    toolsDesc: "텍스트, 이미지, PDF, 데이터 변환 등 자주 필요한 온라인 도구를 브라우저에서 바로 사용할 수 있습니다.",
    explore: "서비스 살펴보기", featured: "대표 서비스", learnMore: "서비스 열기",
    moneyKicker: "함께 기록하고 관리하는 가계부", moneyHeading: "가족과 친구가 함께 쓰는 무료 가계부",
    moneyBody: "가계부를 만들고 초대한 사용자를 멤버로 추가해 수입과 지출을 함께 기록하세요. 계좌와 카테고리, 예산, 캘린더, 리포트와 월 결산까지 한곳에서 관리할 수 있습니다.",
    features: ["수입·지출과 계좌 기록", "초대와 멤버 권한 관리", "월·카테고리 예산과 캘린더", "월간·연간 리포트와 월 결산"],
    calculatorsHeading: "필요한 순간 바로 쓰는 계산기", calculatorsBody: "자주 찾는 금융·수학·생활 계산기를 한곳에서 확인하고 바로 계산해 보세요.",
    toolsHeading: "브라우저에서 바로 쓰는 도구", toolsBody: "이미지와 PDF를 다듬고, 텍스트와 데이터를 편하게 변환하세요. 별도 설치 없이 사용할 수 있습니다.",
    moreCalculators: "더 많은 계산기 보기", moreTools: "더 많은 도구 보기", footer: "일상에 필요한 서비스를 편리하게.",
    groups: { finance: "금융", math: "수학·변환", life: "생활·날짜", text: "텍스트", image: "이미지", developer: "개발", pdf: "PDF" },
  },
  en: {
    title: "WOORI.TODAY | Shared Budgeting, Calculators & Online Tools",
    description: "A practical home for free shared budgeting, everyday finance and life calculators, and useful image, text, PDF, and developer tools.",
    home: "Home", money: "MoneyBook", calculators: "Calculators", tools: "Tools",
    eyebrow: "Useful services for everyday life", headline: "Everyday essentials, all in one place",
    intro: "Keep a shared household budget, work through everyday calculations, and use handy online tools—all in one simple place.",
    start: "Open MoneyBook", seeCalculators: "Browse calculators", seeTools: "Browse tools",
    moneyTitle: "A free shared budget for everyone",
    moneyDesc: "Invite family, a spouse, or friends to manage one budget together.",
    calcTitle: "Quick answers to everyday calculations",
    calcDesc: "Use practical finance, math, date, and everyday calculators instantly, with no installation.",
    toolsTitle: "Online tools, ready when you are",
    toolsDesc: "Work with text, images, PDFs, and data right in your browser—no installation needed.",
    explore: "Explore our services", featured: "Our services", learnMore: "Open service",
    moneyKicker: "Plan and keep track together", moneyHeading: "A free household budget you can share",
    moneyBody: "Create a budget and invite members to record income and expenses together. Keep accounts, categories, budgets, a calendar, reports, and monthly closing in one place.",
    features: ["Income, expenses, and accounts", "Invitations and member permissions", "Monthly and category budgets with a calendar", "Monthly and yearly reports and closing"],
    calculatorsHeading: "Calculators for the questions that come up", calculatorsBody: "Find practical finance, math, and everyday calculators, then get an answer straight away.",
    toolsHeading: "Useful tools in your browser", toolsBody: "Edit images and PDFs, tidy up text, or convert data—all without installing an app.",
    moreCalculators: "See all calculators", moreTools: "See all tools", footer: "A little help for everyday life.",
    groups: { finance: "Finance", math: "Math & conversion", life: "Everyday & dates", text: "Text", image: "Images", developer: "Developer", pdf: "PDF" },
  },
  ja: {
    title: "WOORI.TODAY | 共有家計簿・計算ツール・オンラインツール",
    description: "家族で使える無料の共有家計簿、金融や暮らしの計算ツール、画像・テキスト・PDF・開発者向けツールをまとめて利用できます。",
    home: "ホーム", money: "家計簿", calculators: "計算ツール", tools: "ツール",
    eyebrow: "毎日の暮らしに役立つサービス", headline: "暮らしに必要なサービスを、ひとつの場所に",
    intro: "家計簿からさまざまな計算ツール、オンラインツールまで。毎日よく使う機能を手軽に利用できます。",
    start: "家計簿を始める", seeCalculators: "計算ツールを見る", seeTools: "ツールを見る",
    moneyTitle: "無料で始める共有家計簿", moneyDesc: "家族や夫婦、友人を招待して、ひとつの家計簿を一緒に管理できます。",
    calcTitle: "必要な計算をすばやく簡単に", calcDesc: "金融、数学、暮らし、日付の計算ツールをインストール不要ですぐに使えます。",
    toolsTitle: "インストール不要のオンラインツール", toolsDesc: "テキスト、画像、PDF、データ変換など、よく使うツールをブラウザーですぐに利用できます。",
    explore: "サービスを見る", featured: "サービス一覧", learnMore: "サービスを開く",
    moneyKicker: "一緒に記録して管理する家計簿", moneyHeading: "家族や友人と使える無料の家計簿",
    moneyBody: "家計簿を作成し、招待したメンバーと収入や支出を記録できます。口座やカテゴリ、予算、カレンダー、レポート、月締めまでまとめて管理できます。",
    features: ["収入・支出と口座の記録", "招待とメンバー権限の管理", "月別・カテゴリ別予算とカレンダー", "月次・年次レポートと月締め"],
    calculatorsHeading: "必要なときにすぐ使える計算ツール", calculatorsBody: "金融、数学、暮らしに役立つ計算ツールを探して、その場ですぐ計算できます。",
    toolsHeading: "ブラウザーですぐ使える便利なツール", toolsBody: "画像やPDFの編集、テキストやデータの変換を、アプリのインストールなしで行えます。",
    moreCalculators: "計算ツールをもっと見る", moreTools: "ツールをもっと見る", footer: "毎日の暮らしを、もっと便利に。",
    groups: { finance: "金融", math: "数学・変換", life: "暮らし・日付", text: "テキスト", image: "画像", developer: "開発", pdf: "PDF" },
  },
  zh: {
    title: "WOORI.TODAY | 共享记账、计算器与在线工具",
    description: "免费使用共享家庭账本、金融与生活计算器，以及实用的图片、文本、PDF 和开发工具。",
    home: "首页", money: "记账", calculators: "计算器", tools: "工具",
    eyebrow: "日常生活服务，一站使用", headline: "日常所需服务，尽在一处",
    intro: "从共享记账到各类计算器和在线工具，轻松使用日常生活中常用的功能。",
    start: "开始记账", seeCalculators: "查看计算器", seeTools: "查看工具",
    moneyTitle: "免费使用的共享家庭账本", moneyDesc: "邀请家人、伴侣或朋友，一起管理同一本账本。",
    calcTitle: "快速轻松完成所需计算", calcDesc: "金融、数学、生活和日期计算器，无需安装即可使用。",
    toolsTitle: "无需安装，打开即用的在线工具", toolsDesc: "在浏览器中使用文本、图片、PDF 和数据转换等常用工具。",
    explore: "探索服务", featured: "精选服务", learnMore: "打开服务",
    moneyKicker: "一起记录与管理家庭收支", moneyHeading: "与家人朋友共享的免费账本",
    moneyBody: "创建账本并邀请成员共同记录收入与支出。账户、分类、预算、日历、报表和月度结账都可集中管理。",
    features: ["记录收入、支出和账户", "邀请成员并管理权限", "月度及分类预算与日历", "月度、年度报表和月度结账"],
    calculatorsHeading: "需要时马上使用计算器", calculatorsBody: "查找实用的金融、数学和生活计算器，立即得出结果。",
    toolsHeading: "浏览器中的实用工具", toolsBody: "编辑图片和 PDF，整理文本或转换数据，无需安装应用。",
    moreCalculators: "查看更多计算器", moreTools: "查看更多工具", footer: "让日常生活更简单。",
    groups: { finance: "金融", math: "数学与换算", life: "生活与日期", text: "文本", image: "图片", developer: "开发", pdf: "PDF" },
  },
} as const;

export type Messages = (typeof messages)[Locale];
export const alternates = (path = "") => ({ languages: { ko: `${origin}/ko${path}`, en: `${origin}/en${path}`, ja: `${origin}/ja${path}`, zh: `${origin}/zh${path}`, "x-default": `${origin}/ko${path}` } });

export const calculators = [
  { slug: "compound-interest", category: "finance", names: { ko: "복리 계산기", en: "Compound interest", ja: "複利計算", zh: "复利计算器" } },
  { slug: "savings-interest", category: "finance", names: { ko: "적금 이자 계산기", en: "Savings interest", ja: "積立預金の利息", zh: "定期储蓄利息" } },
  { slug: "loan-interest", category: "finance", names: { ko: "대출 이자 계산기", en: "Loan repayment", ja: "ローン返済計算", zh: "贷款还款计算器" } },
  { slug: "ltv", category: "finance", names: { ko: "LTV 계산기", en: "LTV calculator", ja: "LTV計算", zh: "LTV 计算器" } },
  { slug: "percentage", category: "math", names: { ko: "퍼센트 계산기", en: "Percentage calculator", ja: "パーセント計算", zh: "百分比计算器" } },
  { slug: "discount", category: "math", names: { ko: "할인 계산기", en: "Discount calculator", ja: "割引計算", zh: "折扣计算器" } },
  { slug: "change-rate", category: "math", names: { ko: "증감률 계산기", en: "Change rate", ja: "増減率計算", zh: "增减率计算器" } },
  { slug: "ratio", category: "math", names: { ko: "비율 계산기", en: "Ratio calculator", ja: "比率計算", zh: "比例计算器" } },
  { slug: "unit-converter", category: "math", names: { ko: "단위 변환 계산기", en: "Unit converter", ja: "単位変換", zh: "单位换算器" } },
  { slug: "bmi", category: "life", names: { ko: "BMI 계산기", en: "BMI calculator", ja: "BMI計算", zh: "BMI 计算器" } },
  { slug: "date-difference", category: "life", names: { ko: "날짜 차이 계산기", en: "Date difference", ja: "日付の差を計算", zh: "日期间隔计算器" } },
  { slug: "dday", category: "life", names: { ko: "D-Day 계산기", en: "D-Day calculator", ja: "D-Day計算", zh: "倒数日计算器" } },
];

export const tools = [
  { slug: "character-count", category: "text", names: { ko: "글자 수 세기", en: "Character counter", ja: "文字数カウント", zh: "字数统计" } },
  { slug: "text-compare", category: "text", names: { ko: "텍스트 비교", en: "Text compare", ja: "テキスト比較", zh: "文本比较" } },
  { slug: "json-formatter", category: "developer", names: { ko: "JSON 정리 도구", en: "JSON formatter", ja: "JSON整形", zh: "JSON 格式化" } },
  { slug: "json-validator", category: "developer", names: { ko: "JSON 유효성 검사", en: "JSON validator", ja: "JSON検証", zh: "JSON 校验" } },
  { slug: "csv-to-json", category: "developer", names: { ko: "CSV를 JSON으로 변환", en: "CSV to JSON", ja: "CSVからJSONへ変換", zh: "CSV 转 JSON" } },
  { slug: "base64", category: "developer", names: { ko: "Base64 인코더·디코더", en: "Base64 encoder / decoder", ja: "Base64エンコード・デコード", zh: "Base64 编码与解码" } },
  { slug: "image-resize", category: "image", names: { ko: "이미지 크기 조절", en: "Image resizer", ja: "画像サイズ変更", zh: "图片尺寸调整" } },
  { slug: "image-compress", category: "image", names: { ko: "이미지 압축", en: "Image compressor", ja: "画像圧縮", zh: "图片压缩" } },
  { slug: "png-to-jpg", category: "image", names: { ko: "PNG를 JPG로 변환", en: "PNG to JPG", ja: "PNGからJPGへ変換", zh: "PNG 转 JPG" } },
  { slug: "heic-to-jpg", category: "image", names: { ko: "HEIC를 JPG로 변환", en: "HEIC to JPG", ja: "HEICからJPGへ変換", zh: "HEIC 转 JPG" } },
  { slug: "pdf-merge", category: "pdf", names: { ko: "PDF 합치기", en: "Merge PDFs", ja: "PDFを結合", zh: "合并 PDF" } },
  { slug: "pdf-split", category: "pdf", names: { ko: "PDF 페이지 추출", en: "Split PDF", ja: "PDFを分割", zh: "拆分 PDF" } },
];
