import type { Locale } from "./site";

export const termsContent = {
  ko: {
    title: "WOORI.TODAY 이용약관",
    description: "WOORI.TODAY 계산기, 온라인 도구 및 관련 서비스 이용약관",
    intro: "이 약관은 WOORI.TODAY가 제공하는 포털, 계산기, 온라인 도구 및 관련 서비스의 이용에 적용됩니다. 서비스를 이용하기 전에 약관을 확인해 주세요.",
    sections: [
      { title: "1. 서비스 목적 및 적용 범위", body: "WOORI.TODAY는 일상에 필요한 정보와 기능을 제공하는 포털로서 계산기와 온라인 도구 등 서비스를 운영합니다. 이 약관은 해당 서비스의 이용에 적용됩니다. 일부 서비스에는 별도의 약관이나 안내가 적용될 수 있습니다." },
      { title: "2. 서비스 이용", body: "이용자는 관련 법령과 이 약관을 준수하여 서비스를 이용해야 합니다. 서비스의 정상적인 운영을 방해하거나, 부당한 방법으로 접근하거나, 서비스 또는 다른 이용자에게 피해를 주는 행위를 해서는 안 됩니다." },
      { title: "3. 계산기 및 온라인 도구 결과의 성격", body: "계산기와 온라인 도구가 제공하는 결과와 정보는 입력값 및 일반적인 기준에 따른 참고 자료입니다. 정확성이나 최신성이 항상 보장되는 것은 아니며, 재무·투자·세무·법률·의료 등 분야의 전문가 판단이나 조언을 대체하지 않습니다. 중요한 결정을 내리기 전에 적절한 전문가에게 확인하시기 바랍니다." },
      { title: "4. 사용자 책임", body: "이용자는 입력하는 정보와 서비스 결과의 검토 및 활용에 책임을 집니다. 결과를 중요한 결정에 사용하기 전에 직접 확인해야 하며, 법령이나 제삼자의 권리를 침해하는 방식으로 서비스를 이용해서는 안 됩니다." },
      { title: "5. 서비스 변경 및 중단", body: "서비스의 개선, 보안, 운영상 필요 또는 불가피한 사정에 따라 서비스의 전부 또는 일부가 변경되거나 일시적 또는 영구적으로 중단될 수 있습니다." },
      { title: "6. 지식재산권", body: "서비스에 포함된 콘텐츠, 디자인, 상표 및 소프트웨어에 관한 권리는 WOORI.TODAY 또는 정당한 권리자에게 있습니다. 법령에 따라 허용되거나 권리자의 동의를 받은 경우를 제외하고 이를 무단으로 복제, 배포, 수정하거나 상업적으로 이용할 수 없습니다." },
      { title: "7. 외부 서비스 및 제삼자 링크", body: "서비스에는 외부 사이트나 제삼자 서비스로 연결되는 링크가 포함될 수 있습니다. 해당 서비스는 각 제공자의 약관과 정책에 따라 운영되며, WOORI.TODAY는 외부 서비스의 내용이나 운영을 통제하지 않습니다." },
      { title: "8. 광고", body: "서비스 운영을 위해 Google AdSense 등 제삼자 광고 서비스가 사용될 수 있습니다. 광고의 표시와 관련 처리는 해당 광고 서비스 제공자의 정책 및 설정에 따릅니다." },
      { title: "9. 분석 도구", body: "서비스 이용 현황을 파악하고 개선하기 위해 Google Analytics 등 분석 도구를 사용할 수 있습니다. 정보 처리에 관한 자세한 내용은 개인정보처리방침을 확인해 주세요." },
      { title: "10. 면책", body: "법령이 허용하는 범위에서 WOORI.TODAY는 서비스의 중단이나 오류, 제공된 정보 또는 결과의 이용으로 발생한 손해에 대해 책임을 지지 않습니다. 다만 관련 법령상 배제하거나 제한할 수 없는 책임에는 이 조항이 적용되지 않습니다." },
      { title: "11. 약관 변경", body: "서비스 또는 관련 법령의 변경에 따라 이 약관을 개정할 수 있습니다. 변경된 약관은 이 페이지에 게시한 때부터 적용되며, 중요한 변경은 적절한 방법으로 안내합니다." },
      { title: "12. 문의", body: "서비스 또는 이 약관에 관한 문의는 개인정보처리방침 페이지에 안내된 문의 경로를 이용해 주세요." },
      { title: "13. MoneyBook 별도 약관", body: "MoneyBook 서비스에는 별도의 이용약관이 적용될 수 있습니다. MoneyBook을 이용할 때는 해당 서비스의 약관을 함께 확인해 주세요." },
    ],
    privacyLabel: "개인정보처리방침 보기",
    moneyLabel: "MoneyBook 이용약관 보기",
    home: "홈", privacy: "개인정보처리방침", terms: "이용약관", footer: "일상에 필요한 서비스를 한곳에서.",
  },
  en: {
    title: "WOORI.TODAY Terms of Use",
    description: "Terms of use for WOORI.TODAY calculators, online tools, and related services.",
    intro: "These terms apply to the WOORI.TODAY portal, calculators, online tools, and related services. Please read them before using our services.",
    sections: [
      { title: "1. Purpose and scope", body: "WOORI.TODAY operates a portal offering services for everyday use, including calculators and online tools. These terms govern your use of those services. Separate terms or notices may apply to certain services." },
      { title: "2. Using the services", body: "You must use the services in accordance with applicable law and these terms. You may not disrupt their operation, gain access through improper means, or engage in conduct that harms the services or other users." },
      { title: "3. Nature of calculator and tool results", body: "Results and information from our calculators and online tools are provided for general reference based on the inputs and commonly used assumptions. We do not guarantee that they will always be accurate or current. They are not a substitute for professional advice or judgment in financial, investment, tax, legal, medical, or other specialized matters. Consult a qualified professional before making important decisions." },
      { title: "4. Your responsibilities", body: "You are responsible for the information you enter and for reviewing and using the results. Check results independently before relying on them for important decisions, and do not use the services in a way that violates the law or another person's rights." },
      { title: "5. Changes or interruptions", body: "We may change or suspend all or part of a service temporarily or permanently for improvements, security, operational needs, or circumstances beyond our control." },
      { title: "6. Intellectual property", body: "Rights to content, designs, trademarks, and software in the services belong to WOORI.TODAY or their respective rights holders. You may not copy, distribute, modify, or use them commercially without authorization, except as permitted by law." },
      { title: "7. External services and third-party links", body: "Our services may link to external websites or third-party services. Those services are governed by their providers' own terms and policies. WOORI.TODAY does not control their content or operation." },
      { title: "8. Advertising", body: "Third-party advertising services, such as Google AdSense, may be used to support our services. Ads and related processing are subject to the advertising provider's policies and settings." },
      { title: "9. Analytics", body: "We may use analytics tools such as Google Analytics to understand how our services are used and to improve them. See our Privacy Policy for details about information handling." },
      { title: "10. Disclaimer", body: "To the extent permitted by law, WOORI.TODAY is not liable for losses arising from service interruptions or errors, or from the use of information or results provided through the services. This does not exclude or limit liability that cannot be excluded or limited under applicable law." },
      { title: "11. Changes to these terms", body: "We may revise these terms as our services or applicable laws change. Revised terms take effect when posted on this page. We will provide notice of material changes through appropriate means." },
      { title: "12. Contact", body: "For questions about our services or these terms, please use the contact details provided on our Privacy Policy page." },
      { title: "13. Separate MoneyBook terms", body: "Separate terms of use may apply to MoneyBook. Please review the terms for that service when using MoneyBook." },
    ],
    privacyLabel: "Read our Privacy Policy", moneyLabel: "Read MoneyBook's terms", home: "Home", privacy: "Privacy", terms: "Terms of Use", footer: "A little help for everyday life.",
  },
  ja: {
    title: "WOORI.TODAY 利用規約",
    description: "WOORI.TODAYの計算機、オンラインツールおよび関連サービスの利用規約です。",
    intro: "本規約は、WOORI.TODAYが提供するポータル、計算機、オンラインツールおよび関連サービスの利用に適用されます。サービスの利用前にご確認ください。",
    sections: [
      { title: "1. サービスの目的と適用範囲", body: "WOORI.TODAYは、計算機やオンラインツールなど、日常に役立つサービスを提供するポータルです。本規約はこれらのサービスの利用に適用されます。一部のサービスには、別途規約や案内が適用される場合があります。" },
      { title: "2. サービスの利用", body: "利用者は、適用される法令および本規約を守ってサービスを利用してください。サービスの運営を妨げる行為、不正な手段によるアクセス、サービスや他の利用者に損害を与える行為は禁止します。" },
      { title: "3. 計算機・オンラインツールの結果について", body: "計算機やオンラインツールの結果および情報は、入力内容と一般的な基準に基づく参考情報です。常に正確または最新であることを保証するものではありません。また、金融・投資・税務・法律・医療などの専門家による判断や助言に代わるものではありません。重要な判断をする前に、適切な専門家にご相談ください。" },
      { title: "4. 利用者の責任", body: "入力する情報と、結果の確認および利用については利用者ご自身が責任を負います。重要な判断に用いる前に内容を確認し、法令や第三者の権利を侵害する方法でサービスを利用しないでください。" },
      { title: "5. サービスの変更・中断", body: "改善、セキュリティ、運営上の必要またはやむを得ない事情により、サービスの全部または一部を変更し、一時的または恒久的に中断する場合があります。" },
      { title: "6. 知的財産権", body: "サービスに含まれるコンテンツ、デザイン、商標およびソフトウェアの権利は、WOORI.TODAYまたは正当な権利者に帰属します。法令で認められる場合や権利者の許可がある場合を除き、無断で複製、配布、改変または商業利用することはできません。" },
      { title: "7. 外部サービスおよび第三者リンク", body: "サービスには、外部サイトや第三者サービスへのリンクが含まれる場合があります。リンク先は各提供者の規約やポリシーに従って運営され、WOORI.TODAYはその内容や運営を管理していません。" },
      { title: "8. 広告", body: "サービスの運営にあたり、Google AdSenseなど第三者の広告サービスを利用する場合があります。広告の表示や関連する処理には、各広告サービス提供者のポリシーおよび設定が適用されます。" },
      { title: "9. 分析ツール", body: "サービスの利用状況を把握し改善するため、Google Analyticsなどの分析ツールを利用する場合があります。情報の取り扱いについては、プライバシーポリシーをご確認ください。" },
      { title: "10. 免責", body: "法令で認められる範囲において、WOORI.TODAYはサービスの中断やエラー、提供された情報または結果の利用により生じた損害について責任を負いません。ただし、適用法令により排除または制限できない責任には本項は適用されません。" },
      { title: "11. 規約の変更", body: "サービスや関連法令の変更に応じて本規約を改定する場合があります。改定後の規約は本ページに掲載した時点で適用され、重要な変更は適切な方法でお知らせします。" },
      { title: "12. お問い合わせ", body: "サービスまたは本規約に関するお問い合わせは、プライバシーポリシーに記載の窓口をご利用ください。" },
      { title: "13. MoneyBookの個別規約", body: "MoneyBookには別途利用規約が適用される場合があります。MoneyBookをご利用の際は、同サービスの規約もご確認ください。" },
    ],
    privacyLabel: "プライバシーポリシーを見る", moneyLabel: "MoneyBook利用規約を見る", home: "ホーム", privacy: "プライバシー", terms: "利用規約", footer: "毎日の暮らしに役立つサービスを。",
  },
  zh: {
    title: "WOORI.TODAY 使用条款",
    description: "WOORI.TODAY 计算器、在线工具及相关服务的使用条款。",
    intro: "本条款适用于 WOORI.TODAY 提供的门户、计算器、在线工具及相关服务。使用服务前，请先阅读本条款。",
    sections: [
      { title: "1. 服务目的与适用范围", body: "WOORI.TODAY 运营提供日常实用服务的门户，包括计算器和在线工具。本条款适用于上述服务。部分服务可能另有适用条款或说明。" },
      { title: "2. 服务使用", body: "用户应遵守适用法律及本条款使用服务。不得妨碍服务正常运行、通过不正当方式访问，或实施损害服务或其他用户的行为。" },
      { title: "3. 计算器及在线工具结果的性质", body: "计算器和在线工具提供的结果及信息，是根据输入内容和通用标准生成的参考资料。我们不保证其始终准确或最新，也不能替代财务、投资、税务、法律、医疗等领域的专业判断或建议。作出重要决定前，请咨询相关专业人士。" },
      { title: "4. 用户责任", body: "用户应对输入的信息以及结果的核实和使用负责。在将结果用于重要决策前，请自行核实；不得以违反法律或侵害他人权利的方式使用服务。" },
      { title: "5. 服务变更或中断", body: "因服务改进、安全、运营需要或不可避免的情况，我们可能变更或暂时、永久中止全部或部分服务。" },
      { title: "6. 知识产权", body: "服务中的内容、设计、商标和软件相关权利归 WOORI.TODAY 或相应权利人所有。除法律允许或取得权利人同意外，不得擅自复制、传播、修改或用于商业用途。" },
      { title: "7. 外部服务及第三方链接", body: "服务中可能包含指向外部网站或第三方服务的链接。此类服务依据各提供方的条款和政策运营，WOORI.TODAY 不控制其内容或运营。" },
      { title: "8. 广告", body: "为支持服务运营，我们可能使用 Google AdSense 等第三方广告服务。广告展示及相关处理遵循相应广告服务提供方的政策和设置。" },
      { title: "9. 分析工具", body: "我们可能使用 Google Analytics 等分析工具了解服务使用情况并加以改进。有关信息处理的详情，请参阅隐私政策。" },
      { title: "10. 免责声明", body: "在法律允许的范围内，对于服务中断或错误，以及使用服务所提供的信息或结果而产生的损失，WOORI.TODAY 不承担责任。本条不排除或限制适用法律规定不得排除或限制的责任。" },
      { title: "11. 条款变更", body: "我们可能根据服务或相关法律的变化修订本条款。修订后的条款自发布于本页面时生效；如有重大变更，我们将通过适当方式告知。" },
      { title: "12. 联系我们", body: "如对服务或本条款有疑问，请通过隐私政策页面所示的联系渠道与我们联系。" },
      { title: "13. MoneyBook 单独条款", body: "MoneyBook 服务可能适用单独的使用条款。使用 MoneyBook 时，请同时查阅该服务的相关条款。" },
    ],
    privacyLabel: "查看隐私政策", moneyLabel: "查看 MoneyBook 使用条款", home: "首页", privacy: "隐私政策", terms: "使用条款", footer: "让日常生活更便利。",
  },
} satisfies Record<Locale, { title: string; description: string; intro: string; sections: { title: string; body: string }[]; privacyLabel: string; moneyLabel: string; home: string; privacy: string; terms: string; footer: string }>;
