import { notFound } from "next/navigation";
import Image from "next/image";
import { isLocale, localeNames, locales, messages, type Locale } from "@/lib/site";
import { calculators, tools } from "@/lib/site";

const serviceHrefs = { money: (locale: Locale) => `/${locale}/money`, calculators: (locale: Locale) => `/${locale}/calculators`, tools: (locale: Locale) => `/${locale}/tools` };
const serviceIcons = { money: "↗", calculators: "∑", tools: "⌘" };

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const copy = messages[locale];
  const services = [
    { key: "money" as const, title: copy.moneyTitle, description: copy.moneyDesc, cta: copy.start, href: serviceHrefs.money(locale), className: "service-card service-card-money" },
    { key: "calculators" as const, title: copy.calcTitle, description: copy.calcDesc, cta: copy.seeCalculators, href: serviceHrefs.calculators(locale), className: "service-card service-card-calculator" },
    { key: "tools" as const, title: copy.toolsTitle, description: copy.toolsDesc, cta: copy.seeTools, href: serviceHrefs.tools(locale), className: "service-card service-card-tools" },
  ];
  const jsonLd = { "@context": "https://schema.org", "@type": "WebSite", name: "WOORI.TODAY", url: `https://www.woori.today/${locale}`, inLanguage: locale, hasPart: ["money", "calculators", "tools"].map((service) => ({ "@type": "WebSite", name: service === "money" ? "MoneyBook" : service === "calculators" ? "Calculator" : "Tools", url: `https://www.woori.today/${locale}/${service === "calculators" ? "calculators" : service}` })) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <header className="site-header"><div className="header-inner">
      <a className="brand" href={`/${locale}`}><Image className="brand-logo" src="/_assets/portal/woori-logo.png" alt="WOORI.TODAY logo" width={419} height={99} priority /></a>
      <nav className="main-nav" aria-label="Primary navigation"><a href={`/${locale}`}>{copy.home}</a><a href={serviceHrefs.money(locale)}>{copy.money}</a><a href={serviceHrefs.calculators(locale)}>{copy.calculators}</a><a href={serviceHrefs.tools(locale)}>{copy.tools}</a></nav>
      <nav className="language-nav" aria-label="Language">{locales.map((item) => <a key={item} href={`/${item}`} lang={item} aria-current={item === locale ? "page" : undefined} title={localeNames[item]}>{item.toUpperCase()}</a>)}</nav>
    </div></header>
    <main>
      <section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot" />{copy.eyebrow}</span><h1>{copy.headline}</h1><p>{copy.intro}</p><a className="button button-primary" href={serviceHrefs.money(locale)}>{copy.explore}<span aria-hidden="true">→</span></a></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-core"><span>W</span></div><div className="orbit-chip chip-money">₩</div><div className="orbit-chip chip-calc">∑</div><div className="orbit-chip chip-tools">⌘</div><span className="art-caption">WOORI.TODAY</span></div></div></section>
      <section className="services section-wrap" aria-labelledby="services-heading"><div className="section-heading"><div><span className="section-kicker">01 / WOORI.TODAY</span><h2 id="services-heading">{copy.featured}</h2></div></div><div className="service-grid">{services.map((service, index) => <article className={service.className} key={service.key}><div className="card-top"><span className="card-index">0{index + 1}</span><span className="card-icon" aria-hidden="true">{serviceIcons[service.key]}</span></div><h3>{service.title}</h3><p>{service.description}</p><a className="text-link" href={service.href}>{service.cta}<span aria-hidden="true">↗</span></a></article>)}</div></section>
      <section className="money-section"><div className="money-layout section-wrap"><div className="money-copy"><span className="section-kicker">02 / MONEYBOOK</span><span className="section-label">{copy.moneyKicker}</span><h2>{copy.moneyHeading}</h2><p>{copy.moneyBody}</p><a className="button button-light" href={serviceHrefs.money(locale)}>{copy.start}<span aria-hidden="true">→</span></a></div><div className="feature-panel"><div className="panel-heading"><span className="panel-dot"/><span>MoneyBook</span><span className="panel-month">{locale === "ko" ? "월별 관리" : locale === "ja" ? "月ごとの管理" : locale === "zh" ? "按月管理" : "Monthly view"}</span></div>{copy.features.map((feature, i) => <div className="feature-row" key={feature}><span className="feature-check">✓</span><span>{feature}</span><span className="feature-number">0{i + 1}</span></div>)}</div></div></section>
      <section className="catalog-section section-wrap"><div className="section-heading"><div><span className="section-kicker">03 / CALCULATOR</span><h2>{copy.calculatorsHeading}</h2><p>{copy.calculatorsBody}</p></div><a className="text-link heading-link" href={serviceHrefs.calculators(locale)}>{copy.moreCalculators}<span aria-hidden="true">→</span></a></div><div className="catalog-grid">{calculators.map((item) => <a className="catalog-card" key={item.slug} href={`/${locale}/calculators/${item.slug}`}><span className="catalog-category">{copy.groups[item.category as keyof typeof copy.groups]}</span><span className="catalog-name">{item.names[locale]}</span><span className="catalog-arrow" aria-hidden="true">↗</span></a>)}</div></section>
      <section className="tools-section"><div className="section-wrap"><div className="section-heading"><div><span className="section-kicker">04 / ONLINE TOOLS</span><h2>{copy.toolsHeading}</h2><p>{copy.toolsBody}</p></div><a className="text-link heading-link" href={serviceHrefs.tools(locale)}>{copy.moreTools}<span aria-hidden="true">→</span></a></div><div className="catalog-grid">{tools.map((item) => <a className="catalog-card tool-card" key={item.slug} href={`/${locale}/tools/${item.slug}`}><span className="catalog-category">{copy.groups[item.category as keyof typeof copy.groups]}</span><span className="catalog-name">{item.names[locale]}</span><span className="catalog-arrow" aria-hidden="true">↗</span></a>)}</div></div></section>
      <section className="closing-cta section-wrap"><div><span className="section-kicker">WOORI.TODAY</span><h2>{copy.eyebrow}</h2></div><div className="closing-links"><a href={serviceHrefs.money(locale)}>{copy.money}<span>↗</span></a><a href={serviceHrefs.calculators(locale)}>{copy.calculators}<span>↗</span></a><a href={serviceHrefs.tools(locale)}>{copy.tools}<span>↗</span></a></div></section>
    </main>
    <footer className="site-footer"><div className="footer-main section-wrap"><div><a className="brand footer-brand" href={`/${locale}`}><Image className="brand-logo" src="/_assets/portal/woori-logo.png" alt="WOORI.TODAY logo" width={419} height={99} /></a><p>{copy.footer}</p></div><div className="footer-services"><span>{copy.featured}</span><a href={serviceHrefs.money(locale)}>{copy.money}</a><a href={serviceHrefs.calculators(locale)}>{copy.calculators}</a><a href={serviceHrefs.tools(locale)}>{copy.tools}</a><a href={`/${locale}/privacy`}>{locale === "ko" ? "개인정보처리방침" : locale === "ja" ? "プライバシーポリシー" : locale === "zh" ? "隐私政策" : "Privacy"}</a></div></div><div className="footer-bottom section-wrap"><span>© {new Date().getFullYear()} WOORI.TODAY</span><nav aria-label="Language">{locales.map((item) => <a key={item} href={`/${item}`} lang={item} aria-current={item === locale ? "page" : undefined}>{localeNames[item]}</a>)}</nav><span className="footer-domain">www.woori.today</span></div></footer>
  </>;
}
